"""Which price decides the bet, which is not the same question as which way it went.

Every backtest in this package settles a window on Binance 5-minute
close-to-close: the close of the bar before the window against the close of the
bar inside it.  Polymarket does not.  A live market's own text says:

    resolve to "Up" if the time-weighted average price (TWAP) of Bitcoin,
    generated by Chainlink, of the time range specified in the title is greater
    than or equal to the price at the beginning of that range

and it names the ``btc-usd-twap-60s-streams`` feed.  That sentence and that feed
admit more than one reading, and they are different bets:

    close_to_close     the last price of the window against the first.  What
                       every number in this repository assumes.
    twap_window        the average price *over* the window against the price at
                       its start.  The literal reading of the sentence.
    twap60_ends        the 60-second average at the end against the 60-second
                       average before the start.  What you get by reading a
                       60-second TWAP stream at two instants.
    twap60_vs_open     the 60-second average at the end against the price at
                       the start.

They agree on a decisive window and disagree on a close one, which is exactly
the population a five-minute strategy lives in.  This module measures the
disagreement from minute bars, and -- given settled windows recorded by
``btc5m watch`` -- scores each rule against what the venue actually paid, which
is the only way to find out which sentence was meant.

A minute bar is not a TWAP.  The proxy used here is the minute's typical price,
``(high + low + close) / 3``, which is the closest thing an OHLC bar offers to
the average price inside it.  Every number this module prints is therefore an
estimate of the disagreement, not the disagreement itself; a rule that changes
a *lot* of outcomes under this proxy would change a lot under the real feed too,
and that is the question being asked.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Sequence

import numpy as np

from .data import BAR_SECONDS, BarSeries
from .gates import DOWN, UP

WINDOW_SECONDS = BAR_SECONDS
MINUTE = 60
MINUTES_PER_WINDOW = WINDOW_SECONDS // MINUTE

# Polymarket resolves Up on ">=", so an exact tie is an Up.
TIE_SIDE = UP

RULE_NAMES = ("close_to_close", "twap_window", "twap60_ends", "twap60_vs_open")

RULE_BLURBS = {
    "close_to_close": "last price of the window vs the first (what the backtests assume)",
    "twap_window": "average over the window vs the price at its start (the literal text)",
    "twap60_ends": "60-second average at the end vs the 60 seconds before the start",
    "twap60_vs_open": "60-second average at the end vs the price at the start",
}


def typical(series: BarSeries) -> np.ndarray:
    """``(high + low + close) / 3``: an OHLC bar's stand-in for its average price."""
    return (series.high + series.low + series.close) / 3.0


@dataclass
class WindowPrices:
    """The prices each candidate rule needs, for every window a minute series covers.

    ``starts`` are window opening seconds.  A window is kept only when all six
    minute bars it needs are present and finite -- the minute closing at the
    start, and the five inside it -- so a gap in the feed drops the window
    instead of quietly changing its outcome.
    """

    starts: np.ndarray
    open_price: np.ndarray        # close of the minute ending at the window start
    pre_twap: np.ndarray          # typical price of that same minute
    window_twap: np.ndarray       # mean typical price of the five minutes inside
    end_twap: np.ndarray          # typical price of the last minute inside
    close_price: np.ndarray       # close of the last minute inside

    def __len__(self) -> int:
        return len(self.starts)


def _empty() -> "WindowPrices":
    nothing = np.array([], dtype=float)
    return WindowPrices(starts=np.array([], dtype=np.int64), open_price=nothing,
                        pre_twap=nothing, window_twap=nothing, end_twap=nothing,
                        close_price=nothing)


def window_prices(minute: BarSeries) -> WindowPrices:
    """Extract every complete five-minute window from a series of minute bars.

    A year of minute bars is half a million rows, so this is done with array
    arithmetic rather than a loop: the candidate heads are the bars closing on a
    five-minute boundary, and a head survives only if the next five bars are
    exactly one minute apart and every price it needs is finite.
    """
    if minute.bar_seconds != MINUTE:
        raise ValueError(f"expected minute bars; this series steps "
                         f"{minute.bar_seconds}s (fetch --interval 1m)")
    ts = np.asarray(minute.ts, dtype=np.int64)
    if len(ts) <= MINUTES_PER_WINDOW:
        return _empty()
    close = np.asarray(minute.close, dtype=float)
    typ = typical(minute)

    # A minute bar closing on a five-minute boundary opens a window.
    heads = np.nonzero((ts % WINDOW_SECONDS == 0)
                       & (np.arange(len(ts)) + MINUTES_PER_WINDOW < len(ts)))[0]
    if not len(heads):
        return _empty()

    # Contiguity: the five bars after the head must be its next five minutes.
    keep = np.ones(len(heads), dtype=bool)
    for k in range(1, MINUTES_PER_WINDOW + 1):
        keep &= ts[heads + k] == ts[heads] + MINUTE * k
    heads = heads[keep]
    if not len(heads):
        return _empty()

    inside = typ[heads[:, None] + np.arange(1, MINUTES_PER_WINDOW + 1)]
    result = WindowPrices(
        starts=ts[heads], open_price=close[heads], pre_twap=typ[heads],
        window_twap=inside.mean(axis=1), end_twap=inside[:, -1],
        close_price=close[heads + MINUTES_PER_WINDOW])

    # A NaN anywhere would decide a window silently, so drop it instead.
    finite = (np.isfinite(result.open_price) & np.isfinite(result.pre_twap)
              & np.isfinite(result.window_twap) & np.isfinite(result.end_twap)
              & np.isfinite(result.close_price))
    if not finite.all():
        result = WindowPrices(
            starts=result.starts[finite], open_price=result.open_price[finite],
            pre_twap=result.pre_twap[finite], window_twap=result.window_twap[finite],
            end_twap=result.end_twap[finite], close_price=result.close_price[finite])
    return result


def _side(after: np.ndarray, before: np.ndarray) -> np.ndarray:
    """UP where it rose, DOWN where it fell, the venue's rule on an exact tie."""
    moved = np.where(after > before, UP, DOWN)
    return np.where(after == before, TIE_SIDE, moved)


def outcomes(prices: WindowPrices) -> dict[str, np.ndarray]:
    """Each candidate rule's winning side, per window."""
    return {
        "close_to_close": _side(prices.close_price, prices.open_price),
        "twap_window": _side(prices.window_twap, prices.open_price),
        "twap60_ends": _side(prices.end_twap, prices.pre_twap),
        "twap60_vs_open": _side(prices.end_twap, prices.open_price),
    }


@dataclass
class Disagreement:
    """How often one rule pays the other side, and where."""

    rule: str
    windows: int
    up_share: float
    differs: int
    differs_on_bet: int | None = None
    bet_windows: int | None = None

    @property
    def rate(self) -> float:
        return self.differs / self.windows if self.windows else float("nan")

    @property
    def bet_rate(self) -> float:
        if not self.bet_windows or self.differs_on_bet is None:
            return float("nan")
        return self.differs_on_bet / self.bet_windows


def compare(prices: WindowPrices, bet_starts: Iterable[int] | None = None,
            baseline: str = "close_to_close") -> list[Disagreement]:
    """Every rule against ``baseline``, overall and on the windows actually bet."""
    sides = outcomes(prices)
    base = sides[baseline]
    mask = None
    if bet_starts is not None:
        wanted = set(int(s) for s in bet_starts)
        mask = np.array([int(s) in wanted for s in prices.starts], dtype=bool)
    out = []
    for name in RULE_NAMES:
        side = sides[name]
        differs = side != base
        out.append(Disagreement(
            rule=name, windows=len(prices),
            up_share=float(np.mean(side == UP)) if len(prices) else float("nan"),
            differs=int(np.sum(differs)),
            differs_on_bet=None if mask is None else int(np.sum(differs & mask)),
            bet_windows=None if mask is None else int(np.sum(mask)),
        ))
    return out


def render_comparison(rows: Sequence[Disagreement],
                      baseline: str = "close_to_close") -> str:
    lines = [
        "Which price decides the bet, measured on minute bars",
        f"  baseline: {baseline} -- {RULE_BLURBS[baseline]}",
        f"  windows:  {rows[0].windows:,}" if rows else "  no windows",
        "",
        "  rule              up share   pays the other side   on the bars bet",
        "  " + "-" * 66,
    ]
    for row in rows:
        on_bet = ("      --" if row.bet_windows is None
                  else f"{row.differs_on_bet:,}/{row.bet_windows:,} "
                       f"({100.0 * row.bet_rate:.2f}%)")
        lines.append(f"  {row.rule:<16} {100.0 * row.up_share:7.2f}%   "
                     f"{row.differs:>7,} ({100.0 * row.rate:5.2f}%)      {on_bet}")
    lines += [
        "",
        "  A minute bar is not a TWAP: the proxy is the minute's typical price,",
        "  (high + low + close) / 3, so these are estimates of the disagreement.",
        "",
        "  A disagreement rate is not a loss. If the side that gets paid flips on",
        "  a fraction f of windows, and the flips fall independently of whether",
        "  the bet was right, a hit rate p becomes p - f(2p - 1): at p = 53%, a 5%",
        "  flip rate costs a third of a point, and it takes a 21% flip rate to",
        "  erase a 1.3-point edge. That is the benign case, and it is the one",
        "  this table describes.",
        "  The malign case is flips that land on the bets the signal got right,",
        "  which costs the full rate. Independence cannot be assumed here: the",
        "  windows where the rules disagree are the close ones, which is also",
        "  where a five-minute signal does its work. The hit-rate table below is",
        "  the measurement that tells them apart; this one only says how often",
        "  the rules part company.",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# what the strategy would actually have been paid
# --------------------------------------------------------------------------- #


@dataclass
class HitRate:
    """One rule's verdict on the bets the strategy actually placed."""

    rule: str
    bets: int
    wins: int

    @property
    def rate(self) -> float:
        return self.wins / self.bets if self.bets else float("nan")


def hit_rates(prices: WindowPrices, bets: dict[int, int]) -> list[HitRate]:
    """Win rate under each rule, on the windows the strategy bet and the side it took.

    This is the number that matters.  A disagreement rate says how often two
    rules pay different sides; this says whether the side the strategy chose was
    the one that got paid, which is what the bankroll sees.
    """
    sides = outcomes(prices)
    index = {int(s): i for i, s in enumerate(prices.starts)}
    pairs = [(index[int(start)], side) for start, side in bets.items()
             if int(start) in index]
    out = []
    for name in RULE_NAMES:
        side = sides[name]
        wins = sum(1 for i, bet_side in pairs if int(side[i]) == int(bet_side))
        out.append(HitRate(rule=name, bets=len(pairs), wins=wins))
    return out


def render_hit_rates(rows: Sequence[HitRate], break_even: float | None = None) -> str:
    lines = ["What the strategy would have been paid, under each rule"]
    if not rows or not rows[0].bets:
        lines.append("  no bet window falls inside these minute bars")
        return "\n".join(lines)
    lines += [f"  signals scored: {rows[0].bets:,}  (tradable signals, before the "
              f"risk layer's limits thin them into bets)",
              "", "  rule              hit rate" +
              ("     vs break-even" if break_even is not None else ""),
              "  " + "-" * (46 if break_even is not None else 30)]
    baseline = next((r for r in rows if r.rule == "close_to_close"), None)
    for row in rows:
        line = f"  {row.rule:<16} {100.0 * row.rate:7.2f}%"
        if break_even is not None:
            line += f"     {100.0 * (row.rate - break_even):+7.2f}%"
        if baseline is not None and row.rule != "close_to_close":
            line += f"   ({100.0 * (row.rate - baseline.rate):+.2f} vs close-to-close)"
        lines.append(line)
    if baseline is not None:
        spread = max(abs(r.rate - baseline.rate) for r in rows)
        lines += [
            "",
            f"  The rules differ by up to {100.0 * spread:.2f} points of hit rate on"
            " these bets.",
            "  Every value in this strategy was chosen against close_to_close. If the",
            "  venue settles on one of the others, that choice was made against the",
            "  wrong target, and the pre-registered runs measured a bet nobody can",
            "  place. Which sentence the venue means is settled by the score below,",
            "  not by reading it again.",
        ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# which rule does the venue actually use?
# --------------------------------------------------------------------------- #


@dataclass
class RuleScore:
    """How a rule did against windows the venue itself has settled."""

    rule: str
    checked: int
    matched: int

    @property
    def rate(self) -> float:
        return self.matched / self.checked if self.checked else float("nan")


def score_against_venue(prices: WindowPrices,
                        settled: dict[int, str]) -> tuple[list[RuleScore], int]:
    """Score each rule against the venue's own outcomes.

    ``settled`` maps a window's opening second to "Up" or "Down", as
    ``btc5m watch`` records it.  Returns the scores and the number of windows on
    which the rules did not all agree -- only those can tell the rules apart, so
    that count is the real sample size.
    """
    sides = outcomes(prices)
    index = {int(s): i for i, s in enumerate(prices.starts)}
    wanted = [(start, side) for start, side in settled.items() if int(start) in index]
    scores = {name: RuleScore(name, 0, 0) for name in RULE_NAMES}
    informative = 0
    for start, venue_side in wanted:
        i = index[int(start)]
        want = UP if str(venue_side).strip().lower() == "up" else DOWN
        predictions = {name: int(sides[name][i]) for name in RULE_NAMES}
        if len(set(predictions.values())) > 1:
            informative += 1
        for name, predicted in predictions.items():
            scores[name].checked += 1
            scores[name].matched += int(predicted == want)
    return [scores[name] for name in RULE_NAMES], informative


def render_venue_scores(scores: Sequence[RuleScore], informative: int) -> str:
    lines = ["Which rule matches what the venue paid",
             f"  settled windows matched to minute bars: "
             f"{scores[0].checked if scores else 0}",
             f"  of those, windows where the rules disagree: {informative}"]
    if not scores or not scores[0].checked:
        lines.append("  nothing to score yet: run `btc5m watch`, then `btc5m settle`, "
                     "and fetch minute bars covering the same hours")
        return "\n".join(lines)
    lines += ["", "  rule              agrees with the venue", "  " + "-" * 44]
    for score in scores:
        lines.append(f"  {score.rule:<16} {score.matched:>4}/{score.checked:<4} "
                     f"({100.0 * score.rate:5.1f}%)")
    if informative == 0:
        lines.append("")
        lines.append("  Every rule agrees on every window here, so this cannot yet "
                     "tell them apart. Only a window they disagree on is evidence, "
                     "and those are the close ones.")
    return "\n".join(lines)
